services:
  - type: web
    name: sofascore-scraper
    env: python
    plan: free
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium --with-deps
    startCommand: gunicorn app:app
